on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Get repository
        uses: actions/checkout@v2

      - name: Use Node.js 14.18
        uses: actions/setup-node@v2
        with:
          node-version: '14.18'

      - name: Build Project
        run: |
          npm install
          npm run build

      - name: SFTP Sync
        uses: swillner/sftp-sync-action@v1.0
        with:
          server: 95.179.198.164
          user: dev_fairdose
          user_private_key: "${{ secrets.deploy_dev_fairdose }}"
          host_public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKT6CYP8Z9XMU5mnqkQM+CTR77L3QzHgz9blzQdQ7ZUn fairdose.dev@gmail.com
          remote: /var/www/fairdose_net
