on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Get repository
        uses: actions/checkout@v2

      - name: Use Node.js 14.18
        uses: actions/setup-node@v2
        with:
          node-version: '14.18'

      - name: Build Project
        run: |
          npm install
          npm run build

      - name: SFTP Deploy
        uses: SamKirkland/web-deploy@1.0.0
        with:
          target-server: fairdose.net
          remote-user: ${{ secrets.SSH_USER }}
          remote-key: ${{ secrets.SSH_PASS }}
          source-path: ./dist/
          destination-path: ${{ secrets.PATH_TO_WWW }}
